# Generated by Django 5.2.8 on 2025-11-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=60, null=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item Review',
                'verbose_name_plural': 'Item Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Item Name')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('REFURBISHED', 'Refurbished')], default='NEW', max_length=20, verbose_name='Condition')),
                ('is_free', models.BooleanField(default=False, verbose_name='Free Item?')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Price')),
                ('is_negotiable', models.BooleanField(default=False)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PUBLISHED', 'Published'), ('DRAFT', 'Draft'), ('SOLD', 'Sold'), ('PENDING', 'Pending')], default='PUBLISHED', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='item_videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
